chore: configure project ci to use sonar cloud
ngworker/lumberjack-next pull request #32
Opened 2022-07-24 22:39 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The Github Actions workflow is not configured to interact with the project Sonar Cloud account.

Fixes: #13 

## What is the new behavior?

- The `sonar-project.properties` configuration is created and includes the eslint and lcov config placeholders
- The `project.json` of all projects got updated with a report configuration for the lint target
- The `project.json` of all projects got updated with a coverage configuration for the test target
- The Sonar Cloud job is created on the CI workflow

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2022-10-06 21:01 UTC, LayZeeDK requested changes

2022-10-06 21:01 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=lint --configuration=report --parallel=2 --max-warnings=0 --skip-nx-cache
issue: When `--skip-nx-cache` is added, we don't use Nx Cloud's distributed cache

2022-10-06 21:01 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=test --configuration=coverage --parallel=1 --maxWorkers=2 --skip-nx-cache
issue: When `--skip-nx-cache` is added, we don't use Nx Cloud's distributed cache

2022-10-06 21:01 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        uses: sonarsource/sonarcloud-github-action@master
issue: Use versioned tag
```suggestion
        uses: sonarsource/sonarcloud-github-action@v1.7
```

2022-10-06 21:01 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +      - uses: actions/checkout@v3
issue: Add Git fetch depth 0 as recommended by the SonarCloud Scan action
```suggestion
      - uses: actions/checkout@v3
        with:
          # necessary for SonarCloud Scan
          fetch-depth: 0
```

2022-10-06 21:01 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +      #   run: yarn configure-sonar-report-paths
issue: We need to replace the `sonar.javascript.lcov.reportPaths` and `sonar.typescript.eslint.reportPaths` placeholders in `sonar-project.properties` using this script

2022-10-06 21:01 UTC, LayZeeDK commented on sonar-project.properties
> +sonar.javascript.lcov.reportPaths=coverage/apps/lumberjack-app/lcov.info,coverage/libs/internal/console-driver/test-util/lcov.info,coverage/libs/internal/test-util/lcov.info,coverage/libs/ngworker/lu
issue: We must have a placeholder here to generate the paths dynamically
```suggestion
sonar.javascript.lcov.reportPaths=<PLACEHOLDER>
```

2022-10-06 21:01 UTC, LayZeeDK commented on sonar-project.properties
> +sonar.eslint.reportPaths=reports/apps/lumberjack-app-e2e/lint/report.json,reports/apps/lumberjack-app/lint/report.json,reports/libs/internal/console-driver/test-util/lint/report.json,reports/libs/int
issue: We must have a placeholder here to generate the paths dynamically
```suggestion
sonar.eslint.reportPaths=<PLACEHOLDER>
```

2022-10-06 21:01 UTC, LayZeeDK commented on libs/internal/console-driver/test-util/CHANGELOG.md
> +# Changelog
issue: This file shouldn't exist.

2022-10-06 21:01 UTC, LayZeeDK commented on libs/internal/test-util/CHANGELOG.md
> +# Changelog
issue: This file shouldn't exist.

2022-10-06 21:01 UTC, LayZeeDK commented on libs/ngworker/lumberjack/CHANGELOG.md
> +# Changelog
suggestion: If the changelog is generated here, we should move the current changelog to this directory.

2022-10-06 21:01 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=lint --configuration=report --parallel=2 --max-warnings=0 --skip-nx-cache
issue: `--all` shouldn't be used with `nx affected`. This parameter is for `nx run-many`.

2022-10-06 21:04 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=test --configuration=coverage --parallel=1 --maxWorkers=2 --skip-nx-cache
issue: `--all` shouldn't be used with `nx affected`. This parameter is for `nx run-many`.

2022-10-06 21:05 UTC, NachoVazquez commented on sonar-project.properties
> +sonar.eslint.reportPaths=reports/apps/lumberjack-app-e2e/lint/report.json,reports/apps/lumberjack-app/lint/report.json,reports/libs/internal/console-driver/test-util/lint/report.json,reports/libs/int
I set the strings manually to test some stuff, but yeah I will put them back.

2022-10-06 21:08 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=test --configuration=coverage --parallel=1 --maxWorkers=2 --skip-nx-cache
I know, but I had a problem where some URLs generated in the reports pointed to my machine user routes. And it was not working because of that.

2022-10-06 21:09 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +      #   run: yarn configure-sonar-report-paths
I removed the scripts to do some manual tests, but yes the idea is to put them back.

2022-10-06 21:10 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +      #   run: yarn configure-sonar-report-paths
I don't see the line that applies to your `--all` comment.

2022-10-06 21:12 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=test --configuration=coverage --parallel=1 --maxWorkers=2 --skip-nx-cache
Some lint reports with local paths from your machine were committed to the repo before the `reports` directory was added to `.gitignore`, but I deleted them in [154e654](https://github.com/ngworker/lumberjack-next/pull/32/commits/154e6548e457cfa4ce696a8672d1b91fede1a7fa).

2022-10-06 21:12 UTC, NachoVazquez commented on libs/internal/console-driver/test-util/CHANGELOG.md
> +# Changelog
Yes, I know. It was generated by `@jsclutery/semver` in a test that I did while testing my PR fixing one of their issues. For some reason is ignoring that I didn't configure semver for that project. 

I think they have a different issue related to that.

2022-10-06 21:12 UTC, NachoVazquez commented on libs/internal/test-util/CHANGELOG.md
> +# Changelog
Same as above. It seems like a semver issue.

2022-10-06 21:14 UTC, NachoVazquez commented on libs/ngworker/lumberjack/CHANGELOG.md
> +# Changelog
It seems that the semver is being generated in all projects. I have to figure it out how to limit that behavior. One way is to move from sync mode to independent mode.

2022-10-06 21:15 UTC, LayZeeDK commented on libs/ngworker/lumberjack/CHANGELOG.md
> +# Changelog
Is there a reason to work on JSCutlery SemVer configuration in this PR?

2022-10-06 21:15 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        run: yarn nx affected --all --target=test --configuration=coverage --parallel=1 --maxWorkers=2 --skip-nx-cache
Maybe that's it, but would the cache still use those files when running the command on my machine first?

2022-10-06 21:17 UTC, NachoVazquez commented on libs/ngworker/lumberjack/CHANGELOG.md
> +# Changelog
I didn't configure it in this PR. I run it in this PR by replacing the node modules to test if my fix there was working, but the idea is to remove all the changes made by running that command.

2022-10-06 21:19 UTC, LayZeeDK commented on libs/ngworker/lumberjack/CHANGELOG.md
> +# Changelog
Okay, let's delete this file as well before approving.

2022-10-07 21:39 UTC, LayZeeDK approved these changes

2022-10-07 21:40 UTC, merged